import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight } from "@/components/ArrowUpRight";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

export const metadata: Metadata = { title: "Our Story | Kim's Nails", description: "Meet the team and care philosophy behind Kim's Nails, a New York nail studio celebrating Black and African American beauty." };

export default function AboutPage() { return <main><SiteHeader /><section className="page-hero shell"><p className="eyebrow">Our story</p><h1>Beauty should feel<br /><em>like care.</em></h1><p>Kim&apos;s Nails is a neighbourhood studio that celebrates Black and African American beauty with an eye for the exceptional and a soft spot for the everyday ritual.</p></section><section className="story shell section-space"><div className="story-image"><Image src="/images/black-hands-finished-nails.png" alt="Black hands with a finished manicure" width={1200} height={1400} /></div><div><p className="eyebrow">A place to exhale</p><h2>Founded on a simple belief: your appointment should be the best part of your day.</h2><p>What started as Kim&apos;s dream of a warmer kind of nail studio has grown into a space where craftsmanship, conversation, and comfort have equal weight.</p><p>Our work honors self-expression in every shade, shape, and finish. Our technicians are always learning, our standards are never relaxed, and our chairs are ready for your next catch-up.</p></div></section><section className="values"><div className="shell"><p className="eyebrow">How we work</p><div className="value-cards"><article><span>01</span><h3>Precision first</h3><p>Detailed prep and intentional technique make every finish last.</p></article><article><span>02</span><h3>Care, always</h3><p>We create a clean, calm space where your comfort is part of the service.</p></article><article><span>03</span><h3>Style is personal</h3><p>We listen, collaborate, and make every set distinctly yours.</p></article></div></div></section><section className="page-cta"><p className="eyebrow light">Come say hello</p><h2>We saved you<br /><em>a seat.</em></h2><Link href="/booking" className="button button-light">Visit the studio <ArrowUpRight /></Link></section><SiteFooter /></main>; }
